name: Build Master

env:
  CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64
  CC_TEST_REPORTER_ID: ${{ secrets.SIMPLE_SERVICE_CODECLIMATE_ID }}

on:
  pull_request:

  push:
    branches:
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ["2.7.0", "3.2.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.14
          bundle install --jobs 3 --retry 3

      - name: Run tests
        run: RUBYOPT="-E UTF-8" bundle exec rake

      - name: Set ENV for codeclimate (pull_request)
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          echo "GIT_BRANCH=$GITHUB_HEAD_REF" >> "$GITHUB_ENV"
          echo "GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF)" >> "$GITHUB_ENV"
        if: github.event_name == 'pull_request'

      - name: Set ENV for codeclimate (push)
        run: |
          echo "GIT_BRANCH=$GITHUB_REF" >> "$GITHUB_ENV"
          echo "GIT_COMMIT_SHA=$GITHUB_SHA" >> "$GITHUB_ENV"
        if: github.event_name == 'push'

      - name: Download test coverage reporter
        run: curl -L $CC_TEST_REPORTER_URL > cc-test-reporter

      - name: Give test coverage reporter executable permissions
        run: chmod +x cc-test-reporter

      - name: Save coverage
        run: ./cc-test-reporter format-coverage --output coverage/codeclimate.${{ matrix.ruby }}.json

      - uses: actions/upload-artifact@v1
        with:
          name: coverage-${{ matrix.ruby }}
          path: coverage/codeclimate.${{ matrix.ruby }}.json

  upload_coverage:
    runs-on: ubuntu-18.04

    needs: test

    steps:
      - name: Download test coverage reporter
        run: curl -L $CC_TEST_REPORTER_URL > cc-test-reporter

      - name: Give test coverage reporter executable permissions
        run: chmod +x cc-test-reporter

      - uses: actions/download-artifact@v1
        with:
          name: coverage-2.7.0
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-3.2.2
          path: coverage

      - name: Aggregate & upload results to Code Climate
        run: |
          ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
          ./cc-test-reporter upload-coverage
